#include "..\include\doubly_test.h"

CLOVE_RUNNER(TEST, DOUBLY_ITEM_NOT_NULL, DOUBLY_APPEND_HEAD_NOTNULL, DOUBLY_APPEND_CHECK_ITEM_ADDED_CORRECTLY, DOUBLY_CHECKTAIL,DOUBLY_CHECKPOP_EMPTYLIST, DOUBLY_CHECKPOP,
            DOUBLY_CHECKREMOVE_SPECIFICITEM, DOUBLY_CHECKREMOVE_FIRSTITEM, DOUBLY_CHECKREMOVE_LASTITEM,DOUBLY_INSERTAFTHER_EMPTYLIST,DOUBLY_INSERTAFTHER_LASTITEM,
            DOUBLY_INSERTAFTHER_CENTERITEM, DOUBLY_INSERTBEFORE_CENTERITEM, DOUBLY_INSERTBEFORE_FIRSTITEM, DOUBLY_GETLISTSIZE, DOUBLY_GETLISTSIZE_EMPTYLIST,
            DOUBLY_GETITEM_WITHINDEX_OUTOFRANGE, DOUBLY_GET_THEFOURTHITEM_WITHINDEX);